# docker-compose.yml
version: "3"
services:
  app:
    build: .
    depends_on:
      - postgres
    ports:
      - "3000:3000"
      - "9229:9229"
    environment:
      TZ: UTC
      DBURL: "postgres://postgres:postgres_password@postgres:5432/postgres_db"
  postgres:
    expose:
      - 5432
    ports: 
      - "5432:5432"
    image: postgres:11.2-alpine
    environment:
      TZ: UTC
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres_password
      POSTGRES_DB: postgres_db
